name: our_year_in_polaroids
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.8.2
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/january.mp4
    - assets/videos/april.mp4
    - assets/videos/may.mp4
    - assets/videos/march.mp4
    - assets/images/march1.png
    - assets/images/march2.png
    - assets/images/march3.png
    - assets/images/tape.png
    - assets/images/polaroid_tape1.png
    - assets/images/polaroid_tape2.png
    - assets/images/polaroid_tape3.png
    - assets/images/polaroid_tape4.png
    - assets/images/polaroid_tape5.png